# Generated by Django 5.1.7 on 2025-04-05 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_uploadedfile_data_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='data_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
