# Generated by Django 5.1.7 on 2025-04-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_alter_uploadedfile_data_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='data_uploaded',
            new_name='date_uploaded',
        ),
    ]
