# Generated by Django 5.1.7 on 2025-04-15 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_rename_data_uploaded_uploadedfile_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastResumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='history/')),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedResumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField()),
            ],
        ),
    ]
