# Generated by Django 4.2.7 on 2025-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_pastresumes_processedresumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('processing_score', models.FloatField()),
                ('file_path', models.CharField(max_length=255)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
