# Generated by Django 4.2.7 on 2025-05-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_processedresume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedresume',
            old_name='document_name',
            new_name='resume_name',
        ),
    ]
