# Generated by Django 4.2.7 on 2025-05-10 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0007_rename_document_name_processedresume_resume_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedResumes',
        ),
        migrations.AddField(
            model_name='processedresume',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
