# Generated by Django 4.2.7 on 2025-05-12 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0009_processedresumetext_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedresumetext',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
