"""
Django settings for fairscan project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(0rtge)l@=luo=w=qp68t!ryqb3*6-@c2(96q8j&h^@r99!y%8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'channels',
    'scan',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fairscan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]


# Keep your existing WSGI config
WSGI_APPLICATION = 'fairscan.wsgi.application'

# Add this new line for ASGI/Channels
ASGI_APPLICATION = 'fairscan.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fairscan',      # Database name
        'USER': 'root',          # MySQL username
        'PASSWORD': 'root',  # MySQL password
        'HOST': 'localhost',       # Database host (use '127.0.0.1' if needed)
        'PORT': '3306',            # Leave as empty string for default port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Optional
            'charset': 'utf8mb4',  # For emoji support
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'Africa/Harare'  # Zimbabwe timezone (UTC+2)
USE_TZ = True  # This must be True for timezone support
# USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # Add leading slash ← THIS IS CRUCIAL

STATICFILES_DIRS = [
    BASE_DIR / "scan/static",  # Should point to app's static folder
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # Keep this for production

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Set up media file handling
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# handle this DATA_UPLOAD_MAX_NUMBER_FILES 
DATA_UPLOAD_MAX_NUMBER_FILES = 1000  # Change this number to your desired limit

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

X_FRAME_OPTIONS = 'SAMEORIGIN'  # Instead of 'DENY'

# FILE_CONTENT_TYPE_OVERWRITES = {
#     'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
# }

LOGIN_URL = '/login/'  # Or whatever path you prefer
LOGIN_REDIRECT_URL = 'my_home'  # This can be a URL name from urls.py or an actual path like '/home/'
LOGOUT_REDIRECT_URL = 'login'  # Where to go after logout

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_TASK_ROUTES ={
    'scan.task.long_running_task':{'queue':"longrun"},
    'scan.task.process_resume_chain':{'queue':"chainprocessing"},
    'scan.task.process_single_resume':{'queue':"singleprocessing"}
}

CELERY_TASK_TRACK_STARTED = True  # Track when tasks start
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 60  # 1 minute

CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_TASK_IGNORE_RESULT = True  # For tasks that don't need results stored

# # Model files
# MODELS_DIR = os.path.join(BASE_DIR, 'scan.main_engine', 'models')
# ONTOLOGY_DIR = os.path.join(BASE_DIR, 'scan.main_engine')

# # Specific files
# MODEL_FILE = 'Mistral-7B-Instruct-v0.3-Q3_K_L.gguf'
# ONTOLOGY_FILE = 'ontology.txt'